spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/osdeving/spring-cloud-config-server
                    username: osdeving
                    password: ${GITHUB_TOKEN}
    application:
        name: config-server

server:
    port: 8888
